package gui.util;

public enum GameResult {
    CHECKMATE, RESIGN, TIME, DRAW, STALEMATE, DEAD_POSITION, FIVEFOLD_REPETITION_RULE, SEVENTY_FIVE_MOVE_RULE, THREEFOLD_REPETITION_RULE, FIFTY_MOVE_RULE
}
